<a href="https://colab.research.google.com/github/hikmatfarhat-ndu/CSC645/blob/master/keras_layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Copyright 2020 Hikmat Farhat

### Callable Objects in Python

In [53]:
class myclass:
  def __init__(self):
    self.x=2
  def __call__(self,y):
    return self.x*y 

In [54]:
c=myclass()
c(4)

8

In [55]:
import tensorflow as tf
from tensorflow import keras

In [103]:
class Linear(keras.layers.Layer):
    def __init__(self,output_dim):
        super(Linear, self).__init__()
        self.output_dim=output_dim
    def build(self,input_shape):
        print("calling build")
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value=w_init(shape=(input_shape[-1], self.output_dim), dtype="float32"),
            trainable=True,
        )
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(
            initial_value=b_init(shape=(self.output_dim,), dtype="float32"), trainable=True
        )

    def call(self, inputs):
        print("calling call")
        return tf.matmul(inputs, self.w)+self.b

In [104]:
linear_layer = Linear(4)
y = linear_layer(x)
print(y)
#print(y)

calling build
calling call
tf.Tensor(
[[-5.1486556e-04  5.6377670e-05 -2.2215821e-04 -1.4420119e-04]
 [-5.1486556e-04  5.6377670e-05 -2.2215821e-04 -1.4420119e-04]], shape=(2, 4), dtype=float32)


In [105]:
input=keras.Input(shape=(2,2))
first=Linear(4)(input)
second=Linear(4)(first)
model=tf.keras.models.Model(input,second)
y=tf.ones((2,2))
print("running model")
x=model(y)
print(x)

calling build
calling call
calling build
calling call
running model
calling call
calling call
tf.Tensor(
[[-0.00132059  0.00371666  0.00031399 -0.00136844]
 [-0.00132059  0.00371666  0.00031399 -0.00136844]], shape=(2, 4), dtype=float32)
