In [74]:
import torch
torch.manual_seed(6)
x = torch.randn(4, 4, requires_grad=True)
y = torch.randn(4, 4, requires_grad=True)
u = torch.randn(4, 4, requires_grad=True)
z = x * y*u
l = z.sum()
l.backward()
print(x.grad)
print(y.grad)


tensor([[-2.8918,  0.4742,  0.6208,  0.3573],
        [-0.0795,  0.4714,  2.0265,  0.6418],
        [ 0.9364, -0.0040, -0.2763,  0.8219],
        [ 0.4053,  0.1325, -0.0042, -0.3059]])
tensor([[-2.3667, -0.2812, -2.5162, -1.1943],
        [ 0.2673, -0.0846, -0.6763,  0.1132],
        [ 0.3349, -0.0052, -0.7993, -0.3788],
        [-0.3790, -0.4033, -0.3808,  1.2394]])


In [75]:

torch.manual_seed(6)
x = torch.randn(4, 4, requires_grad=True)
y = torch.randn(4, 4, requires_grad=True)
u = torch.randn(4, 4, requires_grad=True)
z = x * y*u

l = z.sum()


In [83]:
import inspect

dl = torch.tensor(1.)
back_sum = l.grad_fn
dz = back_sum(dl)
back_mul = back_sum.next_functions[0][0]

dx, dy = back_mul(dz)
back_x = back_mul.next_functions[0][0]
back_x(dx)
back_y = back_mul.next_functions[1][0]
back_y(dy)
print(dir(back_sum))
#print(back_sum._register_hook_dict(1))
#print(type(back_mul))
#print(id(back_mul))
#print(back_x)
#print(x.grad)
#print(z.grad)
print(l.equal(back_mul._saved_self))

#q=[]
#q.append(back_sum)
#while len(q)!=0:
#    n=q.pop(0)
#   
#    for next in n.next_functions:
#        q.append(next[0])
#        print(type(n).__name__,"->",type(next[0]).__name__)



['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_register_hook_dict', '_saved_self_sym_sizes', 'metadata', 'name', 'next_functions', 'register_hook', 'register_prehook', 'requires_grad']
False


In [77]:
a, b = torch.randn(2, requires_grad=True).unbind()
c = a+b
print(c.grad_fn.next_functions)

((<UnbindBackward0 object at 0x7faa4b9bf2e0>, 0), (<UnbindBackward0 object at 0x7faa4b9bf2e0>, 1))


In [78]:
x = torch.randn(5, requires_grad=True)
y = x.pow(2)
print(x.equal(y.grad_fn._saved_self))  # True
print(x is y.grad_fn._saved_self)  # True


True
True


In [113]:
x=torch.rand(1,requires_grad=True)
y=torch.rand(1,requires_grad=True)
z=torch.rand(1,requires_grad=True)
w=torch.rand(1,requires_grad=True)
l=x*y*z*w
print(x)
print(y)
print(z)
print(w)
dl=l.grad_fn.next_functions

tensor([0.4389], requires_grad=True)
tensor([0.2748], requires_grad=True)
tensor([0.9068], requires_grad=True)
tensor([0.7684], requires_grad=True)


In [114]:
print(l.grad_fn._saved_self)


tensor([0.1094], grad_fn=<MulBackward0>)


In [121]:
dl[1][0](torch.tensor(1.))

()

In [122]:
print(x.grad,y.grad,z.grad,w.grad)

None None None tensor([1.])
